import turtle

turtle.forward(150)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(80)

turtle.pencolor("Red")
turtle.penup()
turtle.forward(200)
turtle.pendown()
turtle.fillcolor("Orange")
turtle.begin_fill()
turtle.forward(120)
turtle.right(90)
turtle.forward(190)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(190)
turtle.end_fill()
turtle.Screen().exitonclick()